#ifndef CONSTANTES_HPP_INCLUDED
#define CONSTANTES_HPP_INCLUDED

#define SIZE_SCREEN_X 1440
#define SIZE_SCREEN_Y 980

#define SIZE_TABLE_X 28
#define SIZE_TABLE_Y 24
#define SIZE_MENU 300

#define FPS 30.f

#endif // CONSTANTES_HPP_INCLUDED